In [1]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_comp=2
X_reconstr=np.dot(U[:,:n_comp],np.dot(np.diag(S[:n_comp]),VT[:n_comp,:]))
print('Original Matrix\n',X,'\n\n')
print('Reconstructed Matrix\n',X_reconstr,'\n\n')

Original Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 


Reconstructed Matrix
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 


